KutuphaneHi.Web/Controllers/AuthorController.cs
using KutuphaneHi.Data;
using KutuphaneHi.Models;
using Microsoft.AspNetCore.Mvc;

namespace KutuphaneHi.Web.Controllers
{
    public class AuthorController : Controller
    {
        private readonly ApplicationDbContext _context;
        public AuthorController(ApplicationDbContext context)
        {
            _context= context;
        }
        public IActionResult Index()
        {
            return View(_context.Authors.ToList()); //_context.Authors.ToList<Authors>()
        }
        [HttpGet]
        public IActionResult Add()//getir,getirecek
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(Author author)//işlem yap
        {
            _context.Authors.Add(author);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            //Author authorToBeDeleted= _context.Authors.Find(id);
            //_context.Authors.Remove(authorToBeDeleted);
            _context.Authors.Remove(_context.Authors.Find(id));
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        
        public IActionResult Edit(int id)
        {
            //Author author = _context.Authors.Find(id);
            return View(_context.Authors.Find(id));
        }

        [HttpPost]
        public IActionResult Edit(Author author)
        {
            _context.Authors.Update(author);
            _context.SaveChanges();
            return RedirectToAction("Index");
            
        }
    }
}

KutuphaneHi.Web/Controllers/BookController.cs
using KutuphaneHi.Data;
using KutuphaneHi.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace KutuphaneHi.Web.Controllers
{
    public class BookController : Controller
    {
        private readonly ApplicationDbContext _context;
        public BookController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View(_context.Books.Include(b=>b.Authors).Include(b => b.Publishers).Include(b=>b.Category).ToList<Book>());
        }

        [HttpGet]
        public IActionResult Add()
        {
            ViewData["categories"] = _context.Categories.ToList();
            ViewData["authors"] = _context.Authors.ToList();
            ViewData["publishers"] = _context.Publishers.ToList();

            return View();
        }

        [HttpPost]
        public IActionResult Add(Book book, List<int>Publishers, List<int> Authors)
        {
            foreach(int id in Publishers)
                book.Publishers.Add(_context.Publishers.Find(id));
            

            foreach(int id in Authors)
                book.Authors.Add(_context.Authors.Find(id));

            _context.Books.Add(book);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            _context.Books.Remove(_context.Books.Find(id));
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Edit(int id)
        {
            var kategoriListesi = ViewData["categories"] as List<Category>;
            var yazarListesi = ViewData["authors"] as List<Author>;
            var yayinEviListesi = ViewData["publishers"] as List<Publisher>;
            Book book = _context.Books.Include(b=>b.Authors).Include(b=>b.Publishers).FirstOrDefault(b=>b.Id==id);
            return View(book);
        }
        [HttpPost]
        public IActionResult Edit(Book book)
        {
            
            _context.Books.Update(book);
            _context.SaveChanges();
            return RedirectToAction("Index");

        }
    }
}

KutuphaneHi.Web/Controllers/CategoryController.cs
using KutuphaneHi.Data;
using KutuphaneHi.Models;
using Microsoft.AspNetCore.Mvc;

namespace KutuphaneHi.Web.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ApplicationDbContext _context;
        public CategoryController(ApplicationDbContext context)
        {
            _context= context;
        } 
        public IActionResult Index()
        {
            return View(_context.Categories.ToList<Category>());
        }

        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(Category category)
        {
            _context.Categories.Add(category);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Edit()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Edit(Category category)
        {
            _context.Categories.Update(category);
            _context.SaveChanges();
            return RedirectToAction("Index");   
        }

        public IActionResult Delete(int id)
        {
            _context.Categories.Remove(_context.Categories.Find(id));
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        
    }
}

KutuphaneHi.Web/Controllers/HomeController.cs
using KutuphaneHi.Data;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace KutuphaneHi.Web.Controllers
{
    public class HomeController : Controller
    {
        public HomeController(ApplicationDbContext context)
        {
            //var result = context.Books.First();
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }
    }
}

KutuphaneHi.Web/Controllers/PublisherController.cs
using KutuphaneHi.Data;
using KutuphaneHi.Models;
using Microsoft.AspNetCore.Mvc;

namespace KutuphaneHi.Web.Controllers
{
    public class PublisherController : Controller
    {
        private readonly ApplicationDbContext _context;
        public PublisherController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View(_context.Publishers.ToList<Publisher>());
            
        }

       
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(Publisher publisher)
        {
            _context.Publishers.Add(publisher);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        
        public IActionResult Edit(int id)
        {
            return View(_context.Publishers.Find(id));

        }

        [HttpPost]
        public IActionResult Edit(Publisher publisher)
        {
            _context.Publishers.Update(publisher);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            //_context.Publishers.Find(id);
            _context.Publishers.Remove(_context.Publishers.Find(id));
            _context.SaveChanges();
            return RedirectToAction("Index");
           

        }
    }
}

KutuphaneHi.Web/Views/Author/Add.cshtml
@model Author

<form class="form" method="post">
    <label asp-for="Name" class="form-label">Author Name:</label>
    <input asp-for="Name" class="form-control" placeholder ="Please enter an author"/>

    <label asp-for="Biography" class="form-label">Biography:</label>
    <textarea asp-for="Biography" class="form-control" rows="5" placeholder="Please enter a biography">Please enter a biography</textarea>

    <button type="submit" class="btn btn-primary">Add</button>
    <button type="reset" class="btn btn-danger">Clear</button>

</form>

KutuphaneHi.Web/Views/Author/Edit.cshtml
@model Author

<form class="form" method="post">
    <label asp-for="Name" class="form-label">Author Name:</label>
    <input asp-for="Name" class="form-control" value="@Model.Name" placeholder="Please enter an author" />

    <label asp-for="Biography" class="form-label">Biography:</label>
    <textarea asp-for="Biography" class="form-control" rows="5" placeholder="Please enter a biography">@Model.Biography</textarea>

    <button type="submit" class="btn btn-primary">Update</button>
    <button type="reset" class="btn btn-danger">Clear</button>

</form>

KutuphaneHi.Web/Views/Author/Index.cshtml
@model List<Author>

<a class="btn btn-primary" asp-action="Add" asp-controller="Author">Add Author</a>

@*@foreach(Author author in Model)
{
    <h1>@author.Name</h1>
}
*@

<table class="table table-striped table-hover">
   <thead>
       <tr>
           <th>Id</th>
           <th>Author Name</th>
           <th>Biography</th>
           <th>Actions</th>
       </tr>
   </thead>
   <tbody>
       @foreach(var author in Model)
       {
           <tr>
               <td>@author.Id</td>
               <td>@author.Name</td>
               <td>@author.Biography</td>
               <td><a onclick="return confirm('Are you sure you want to delete this?')" asp-controller="Author" asp-action="Delete" asp-route-id="@author.Id" class="btn btn-danger">Delete</a>

                    <a asp-controller="Author" asp-action="Edit" asp-route-id="@author.Id" class="btn btn-success">Edit</a>


               </td>
           </tr>
       }
   </tbody>


</table>

KutuphaneHi.Web/Views/Book/Add.cshtml
@model Book
@{
    var kategoriListesi = ViewData["categories"] as List<Category>;
    var yazarListesi = ViewData["authors"] as List<Author>;
    var yayinEviListesi = ViewData["publishers"] as List<Publisher>;
}
<form method="post">
    <label asp-for="Name">Book name</label>
    <input asp-for="Name" class="form-control"  placeholder="Please enter a book name" />

    <label asp-for="PageCount">Page Count</label>
    <input asp-for="PageCount" class="form-control" placeholder="please write the number of pages" />

    <label asp-for="ISBN" class="form-label">ISBN Code</label>
    <input asp-for="ISBN" class="form-control" placeholder="please enter ISBN" />

    <label asp-for=Category class="form-label" asp-for="CategoryId">Select a category</label>
    <select asp-for="CategoryId" class="form-select" asp-items="@(new SelectList(kategoriListesi,"Id","Name"))"></select>

    <label asp-for="Authors" class="form-label" asp-for="Authors">Select Author(s)</label>
    <select asp-for="Authors" class="form-select" asp-items="@(new MultiSelectList(yazarListesi,"Id","Name"))"></select>

    <label asp-for="Publishers" class="form-label" asp-for="Publishers">Select Publisher(s)</label>
    <select asp-for="Publishers" class="form-select" asp-items="@(new MultiSelectList(yayinEviListesi,"Id","Name"))"></select>

    <button type="submit" class="btn btn-secondary">Add</button>
    <button type="reset" class="btn btn-danger">Clear</button>
</form>

KutuphaneHi.Web/Views/Book/Edit.cshtml
@model Book
@{
    var kategoriListesi = ViewData["categories"] as List<Category>;
    var yazarListesi = ViewData["authors"] as List<Author>;
    var yayinEviListesi = ViewData["publishers"] as List<Publisher>;
}
<form class="form" method="post">
    <label asp-for="Name">Book name</label>
    <input asp-for="Name" class="form-control" value="@Model.Name" placeholder="Please enter a book name" />

    <label asp-for="PageCount">Page Count</label>
    <input asp-for="PageCount" class="form-control" value="@Model.PageCount" placeholder="write the number of pages" />

    <label asp-for="ISBN" class="form-label">ISBN Code</label>
    <input asp-for="ISBN" class="form-control" value="@Model.ISBN" placeholder="please enter ISBN" />

    <label asp-for=Category class="form-label" asp-for="CategoryId">Select a category</label>
    <select asp-for="CategoryId" class="form-select" asp-items="@(new SelectList(kategoriListesi,"Id","Name"))"></select>

    <label asp-for="Authors" class="form-label" asp-for="Authors">Select Author(s)</label>
    <select asp-for="Authors" class="form-select" asp-items="@(new MultiSelectList(yazarListesi,"Id","Name"))"></select>

    <label asp-for="Publishers" class="form-label" asp-for="Publishers">Select Publisher(s)</label>
    <select asp-for="Publishers" class="form-select" asp-items="@(new MultiSelectList(yayinEviListesi,"Id","Name",Model.Publishers))"></select>

    <button type="submit" class="btn btn-secondary">Add</button>
    <button type="reset" class="btn btn-danger">Clear</button>
</form>

KutuphaneHi.Web/Views/Book/Index.cshtml
@model List<Book>

<a class="btn btn-dark" asp-action="Add" asp-controller=" Book" asp-controller="Book">Add</a>

<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>Id</th>
            <th>Book Name</th>
            <th>Page Count</th>
            <th>ISBN</th>
            <th>Authors</th>
            <th>Publishers</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var book in Model)
        {
            <tr>
                <td>@book.Id</td>
                <td>@book.Name</td>
                <td>@book.PageCount</td>
                <td>@book.ISBN</td>
                <td>
                    @foreach(var author in book.Authors)
                    {
                        @author.Name<br/>
                    }
                </td>
                <td>
                    @foreach(var publishers in book.Publishers)
                    {
                        @publishers.Name<br />
                    }
                </td>
                <td>
                  
                    <a onclick="return confirm('Are you sure you want to delete this?')" asp-controller="Book" asp-action="Delete" asp-route-id="@book.Id" class="btn btn-danger">Delete</a>

                    <a asp-controller="Book" asp-action="Edit" asp-route-id="@book.Id" class="btn btn-success">Edit</a>


                </td>
            </tr>
        }
    </tbody>
</table>

KutuphaneHi.Web/Views/Category/Add.cshtml
@model Category

<form class="form" method="post">
    <label asp-for="Name" class="form-label">Name:</label>
    <input asp-for="Name" class="form-control" />

    <button class="btn btn-dark" type="submit">Add</button>
    <button class="btn btn-danger" type="reset">Clear</button>
</form>
    

KutuphaneHi.Web/Views/Category/Edit.cshtml
@model Category

<form class="form" method="post">

    <label asp-for="Name" class="form-label">Category Name</label>
    <input asp-for="Name" class="form-control"/>

    <button type="submit" class="btn btn-secondary"></button>
    <button type="reset" class="btn btn-danger"></button>
</form>

KutuphaneHi.Web/Views/Category/Index.cshtml
@model List<Category>

    <a asp-controller="Category" asp-action="Add">Add</a>

    <table class="table table-striped table-hover">
        <thead>
        <td>
            <tr>
              <th>Id</th>
              <th>Name</th>
              <th>İşlemler</th>
            </tr>
        </td>
    </thead>
    <tbody>
    @foreach(var item in Model)
     {  <tr>
         <td>@item.Id</td>
         <td>@item.Name</td>
         <td><a asp-action="Edit" class="btn btn-dark" asp-controller="Category" asp-route-id="@item.Id">Edit</a> 
          <a asp-action="Delete" class= "btn btn-danger"asp-controller="Category"  asp-route-id="@item.Id">Delete</a>
         </td>
        </tr>
     }
    </table>
    </tbody>

KutuphaneHi.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

KutuphaneHi.Web/Views/Publisher/Add.cshtml
@model Publisher

<form class="form" method="post">
    <label asp-for="Name" class="form-label">Publisher Name:</label>
    <input asp-for="Name" class="form-control" placeholder="Please enter a publisher" />

    <label asp-for="Address" class="form-label">Address:</label>
    <input asp-for="Address" class="form-control" value="@Model.Address" placeholder="enter a publisher address" />

    <button type="submit" class="btn btn-primary">Add</button>
    <button type="reset" class="btn btn-danger">Clear</button>

</form>

KutuphaneHi.Web/Views/Publisher/Edit.cshtml
@model Publisher

<form class="form" method="post">
    <label asp-for="Name" class="form-label">Publisher Name</label>
    <input asp-for="Name" class="form-control" value="@Model.Name" placeholder="enter a publisher name" />

    <label asp-for="Address" class="form-label">Publisher Address</label>
    <input asp-for="Address" class="form-control" value="@Model.Address" placeholder="enter an address" />

    <button class="btn btn-primary" type="submit">Update</button>
    <button class="btn btn-dark" type="reset">Clear</button>
</form>

KutuphaneHi.Web/Views/Publisher/Index.cshtml
@model List<Publisher>

 <a class="btn btn-primary" asp-action="Add" asp-controller="Publisher">Add Publisher</a>

 <table class="table table-striped table hover">
      <thead>
          <tr>
              <th>Publisher Name</th>
              <th>Address</th>
              <th>Actions</th>
          </tr>
      </thead>
      <tbody>
          @foreach(var item in Model)
          {
              <tr>
                   <td>@item.Id</td>
                   <td>@item.Name</td>
                   <td>@item.Address</td>
                <td>
                    <a onclick="return confirm('Are you sure you want to delete this?')" asp-controller="Publisher" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Delete</a>

                    <a asp-controller="Publisher" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-success">Edit</a>


                </td>
              </tr>
          }
      </tbody>
 </table>

KutuphaneHi.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - KutuphaneHi.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/KutuphaneHi.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">KutuphaneHi.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Author" asp-action="Index">Authors</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Publisher" asp-action="Index">Publishers</a>
                      
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="Index">Books</a>

                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Categories</a>

                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - KutuphaneHi.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>